### PR TITLE
Solved the link error in API_METHODS and API_RESOPONSE files.

### PR DESCRIPTION
**Pull request by Shikharishere**

### CODE REVIEW

**Review by stepan-zubkov — APPROVED** [review]
Fine

**Comment by Shikharishere** [comment]
Hey!, @stepan-zubkov did I do any mistake?

**Comment by stepan-zubkov** [comment]
> Hey!, @stepan-zubkov did I do any mistake?

No, I just cannot merge this PR because CI not passed. Dont worry

**Comment by kirillzhosul** [comment]
CI is a bit broken (linters, etc) but tests are fine (anyway there is no code changes).
Closed now.
Reason of that mistake is unknown for me (type or whatever), it is redirecting old ones to API because of Nginx proxy /api/ to api domain (even in it /apis/ one....

**Pull request merged**
